### PR TITLE
Add instructions for Flatpak

### PR DESCRIPTION
**Pull request by SudoVanilla**

### CODE REVIEW

**Review by maximilionus — APPROVED** [review]
Can confirm that this method is working. Although we could change the `<FOLDERNAME>` to `active` as it's linked to the latest release directory.

```bash
[/var/lib/flatpak/app/com.spotify.Client/x86_64/stable]$ ll
active -> d12294...
d12294...
```

**Comment by Edlavio** [comment]
This work for me:

```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -P /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
```

**Comment by SudoVanilla** [comment]
@Nuzair46 @amd64fox I really didn't want to ping, sorry. The PR has been opened for over 2 months now. 
I don't keep my stuff open forever, I will close PR on June 18th if not merged by then.
If you deny this change, you are welcomed to close this PR.

**Comment by Nuzair46** [comment]
Sorry for the delay.
Please ping me in the future.
Thanks for the contribution.

**Review by Nuzair46 — APPROVED** [review]

**Pull request merged**
